export const instagram = 'https://www.instagram.com/shawtyslayz/';

export const products = [
  {
    id: 'kitty',
    name: 'Kitty print wide legs',
    image: 'cute-trouser-product',
    detail: 'cute-trouser-detail',
    category: 'trousers',
    color: 'White / pink',
    price: 2490,
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    alt: 'White wide-leg lounge trousers with kitty faces and pink bows',
    description: 'Relaxed wide-leg trousers with an elastic waist and an all-over kitty-and-bow print. Easy with a fitted tee, oversized shirt, or the matching black top.',
    fit: 'Relaxed wide leg · mid rise',
    fabric: 'Soft-touch woven fabric',
    care: 'Cold wash · inside out · air dry',
    sizeNote: 'If you sit between sizes, choose the roomier size for the intended relaxed fit.',
    features: ['Elastic waist', 'Relaxed leg', 'Everyday weight'],
    mood: 'sweet',
  },
  {
    id: 'bat',
    name: 'Bat print wide legs',
    image: 'dark-trouser-product',
    detail: 'dark-trouser-campaign',
    category: 'trousers',
    color: 'Black / yellow',
    price: 2490,
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    alt: 'Black wide-leg lounge trousers with repeated yellow bat graphics',
    description: 'The same easy wide-leg shape in a black-and-yellow bat print. Built for monochrome fits when plain black trousers feel too safe.',
    fit: 'Relaxed wide leg · mid rise',
    fabric: 'Soft-touch woven fabric',
    care: 'Cold wash · inside out · air dry',
    sizeNote: 'Choose your usual size for a relaxed fit, or size up if you want extra room through the leg.',
    features: ['Elastic waist', 'Relaxed leg', 'Statement print'],
    mood: 'dark',
  },
  {
    id: 'tee',
    name: 'Spider graphic tee',
    image: 'graphic-tee-product',
    detail: 'graphic-tee-lifestyle',
    category: 'tops',
    color: 'Black / white',
    price: 1990,
    sizes: ['S', 'M', 'L', 'XL'],
    alt: 'Black short-sleeve tee with a large white spider-inspired chest graphic',
    description: 'A black everyday tee with one oversized white graphic. Simple enough to wear on repeat, loud enough to carry the fit.',
    fit: 'Easy unisex fit',
    fabric: 'Cotton jersey',
    care: 'Cold wash · inside out · do not iron print',
    sizeNote: 'Take your usual size for an easy fit. Size up for a looser, dropped look.',
    features: ['Soft jersey', 'Front graphic', 'Unisex shape'],
    mood: 'graphic',
  },
  {
    id: 'plaid',
    name: 'Checkered lounge trousers',
    image: 'plaid-lounge-lifestyle',
    detail: 'plaid-lounge-lifestyle',
    category: 'trousers',
    color: 'Grey / black',
    price: 2290,
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    alt: 'Woman seated in grey checkered wide-leg trousers and a fitted black top',
    description: 'The quieter pair in the rotation: grey-and-black checks, an easy waist, and a loose leg that works with basically everything.',
    fit: 'Relaxed wide leg · mid rise',
    fabric: 'Lightweight woven fabric',
    care: 'Cold wash · gentle cycle · air dry',
    sizeNote: 'Choose your usual size for the intended fit. Size up for a lower, slouchier look.',
    features: ['Elastic waist', 'Easy checks', 'Lightweight feel'],
    mood: 'lowkey',
  },
] as const;

export type Product = (typeof products)[number];
export type ProductId = Product['id'];
export type ProductSize = Product['sizes'][number];

export const formatPrice = (value: number) => `Rs. ${value.toLocaleString('en-PK')}`;
